
# Initial Travic-CI control file. 6.5.15 jhrg

language: cpp
compiler:
  - gcc
#  - clang

# Change this to your needs

# Get, install bison 3
install:
  - wget http://mirrors.kernel.org/gnu/bison/bison-3.0.tar.gz
  - tar -xzvf bison-3.0.tar.gz
  - cd bison-3.0 && ./configure && make -j7
  - sudo make install
  - cd ..
  
# Build from github
# 
# Must decide about $prefix and $PATH
# Also --enable-developer
script:
  - autoreconf --force --install --verbose
  - ./configure && make -j7 && make -j7 check
  - sudo make install
  
# whitelist
branches:
  only:
    - master
