
# Initial Travic-CI control file. 6.5.15 jhrg

language: cpp

compiler:
  - gcc
  - clang

# whitelist
branches:
  only:
    - master

# Use this to prepare the system to install prerequisites or dependencies
#
# Building on Ubuntu, we need uuid-dev, xml and curl
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxml2-dev uuid-dev libcurl4-openssl-dev

# Use this to install any prerequisites or dependencies necessary to run your build
#
# Get, install bison 3
install:
  - wget http://mirrors.kernel.org/gnu/bison/bison-3.0.tar.gz
  - tar -xzvf bison-3.0.tar.gz
  - (cd bison-3.0 && ./configure --prefix=$prefix/deps && make -j7 && sudo make install)
 
# Use this to prepare your build for testing
# e.g. copy database configurations, environment variables, etc.
#
# I set prefix and PATH even though the later is not needs because it'll be required
# with the bes build.
before_script:
  - export prefix=`pwd`/../build
  - export PATH=$prefix/bin:$PATH
  - autoreconf --force --install --verbose
  - ./configure --prefix=$prefix

# All commands must exit with code 0 on success. Anything else is considered failure.
#
# NB: sudo make install failed for clang here, hence the use of --prefix (which we'll
# need anyway later when we build the bes).
script:
  - make -j7
  - make -j7 check
  - make install
  
# after_script:
