# -*- shell-script -*-
#
# Initial Travic-CI control file. 6.5.15 jhrg
# Updated many times... finally using docker (containers). 7.14.15 jhrg

dist: trusty

# Use the docker container-based build systems
sudo: false

language: cpp

compiler: gcc

branches:
  only:
  - master
  - coverity_scan
  - travis
  - /^*-[0-9]+\.[0-9]+\.[0-9]+/

addons:
  ssh_known_hosts: www.opendap.org
  coverity_scan:
    project:
      name: "OPENDAP/libdap4"
    notification_email: jgallagher@opendap.org
    build_command: "make -j7"
    branch_pattern: coverity_scan
  apt:
    packages:
    - libxml2-dev
    - uuid-dev
    - libcurl4-openssl-dev
    - libcppunit-dev
    
before_install:
- pip install --user awscli
- ./ecr_credentials.sh

install:
- aws s3 sync s3://opendap.travis.build/ $prefix
- tar -xzf $prefix/hyrax-dependencies-build.tar.gz
- ls -lR $prefix

before_script:
- autoreconf --force --install --verbose
- ./configure --disable-dependency-tracking --prefix=$prefix/build --enable-developer --enable-asan

# All commands must exit with code 0 on success. Anything else is
# considered failure. Note that each line of 'script' is run, regardless
# of exit status (in the preceding sections, execution stops on the
# first error).

# script:
# - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make -j7 && make check -j7 && make install && make distcheck -j7; fi

jobs:
  include:
  - stage: build
    script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make -j7 && make check -j7; fi
  - stage: build
    script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make distcheck -j7; fi

env:
  global:
  - prefix=$HOME/OPENDAP
  - PATH=$prefix/build/bin:$prefix/bin:/usr/local/bin:$PATH
  # COVERITY_SCAN_TOKEN, created via the "travis encrypt" command using the project repo's public key
  - secure: "OYEzGP6BuDHctPj90EP0y0wjfSyaJs6tN89niLhq82jJfJVGvU2UmXGWACNFakM7xpobVfdwCIYomxgIz43CpNKt4TbuGW8PVIz2EI9Ir/Ne4A3W8pVHBkP8YvzRkiu0pWNeShcsJ4ZmzWEGy9YlPF36/HWai3ZCMEtJsTY8cCo="
  # AWS_ACCESS_KEY_ID for the user 'travis'
  - secure: "Azd20M0X367Glf6YnQXRLXJXGrKkJwKK6X7hKRvNZ1oSPkTLmW1JlUKpsjmstz+oJxZHATMP64fymTkxRmyHU7bNktBkiI3i6k1cFXRPGEhrf2Uftnve/Zy2TEJ6ucnEpYmw5+LyZgAZVNLzFnUrE2FUbzG8I1yO2KYr00nvof4="
  # AWS_SECRET_ACCESS_KEY
  - secure: "lL7WaRHysuAKGLhMBbMyCk8yvRn4mmZeF+W7t4duh7/1DrGiPZ9kQwkfM54r5hLXPeKqqMyDjJs5kATlBgzg68dnwSaLFsbe3TqI9Zj258PgUf1+EYaK+vP9O9brHUUrmtqj6uFGtrP1Dqj2S8AUuTvrYtvSr7vGGitv4++n3AY="

