
# Initial Travic-CI control file. 6.5.15 jhrg

language: cpp

compiler:
  - gcc
  - clang

# whitelist
branches:
  only:
    - master

# Building on Ubuntu, we need uuid-dev, xml and curl
# Get, install bison 3
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxml2-dev uuid-dev libcurl4-openssl-dev
  
install:
  - wget http://mirrors.kernel.org/gnu/bison/bison-3.0.tar.gz
  - tar -xzvf bison-3.0.tar.gz
  - (cd bison-3.0 && ./configure && make -j7 && sudo make install)
 
before_script:
  - autoreconf --force --install --verbose
  - ./configure 

# I used sudo -i so that sudo make install works for clang - a known issue with travis-ci)
# jhrg 6.5.15
script:
  - make -j7
  - make -j7 check
  - sudo -i make install
  
# after_script:
