#
# The libdap build
#
# Initial Travic-CI control file. 6.5.15 jhrg
# Updated many times... finally using docker (containers). 7.14.15 jhrg
#
# Modified to push the result of a successful build up to an AWS S3
# bucket. jhrg 2.24.18

dist: trusty

sudo: false

language: cpp

compiler: gcc

branches:
  only:
  - master
  - coverity_scan
  - debian
  #- /^version-.*$/

addons:
  coverity_scan:
    project:
      name: "OPENDAP/libdap4"
    notification_email: jgallagher@opendap.org
    build_command_prepend: ./configure --disable-dependency-tracking --prefix=$prefix
    build_command: "make -j7"
    branch_pattern: coverity_scan
  apt:
    packages:
    - libxml2-dev
    - uuid-dev
    - libcurl4-openssl-dev
    - libcppunit-dev 
    - build-essential
    - lintian
    - fakeroot
    
env:
  global:
  # NB: This value of $prefix must be shared between the hyrax-deps, libdap and bes builds.
  - prefix=$HOME/install
  - PATH=$prefix/bin:$PATH
  - TESTSUITEFLAGS=-j7  
  # COVERITY_SCAN_TOKEN, created via the "travis encrypt" command using the project repo's public key
  - secure: "OYEzGP6BuDHctPj90EP0y0wjfSyaJs6tN89niLhq82jJfJVGvU2UmXGWACNFakM7xpobVfdwCIYomxgIz43CpNKt4TbuGW8PVIz2EI9Ir/Ne4A3W8pVHBkP8YvzRkiu0pWNeShcsJ4ZmzWEGy9YlPF36/HWai3ZCMEtJsTY8cCo="
  # AWS_ACCESS_KEY_ID for the user 'travis'
  - secure: "Azd20M0X367Glf6YnQXRLXJXGrKkJwKK6X7hKRvNZ1oSPkTLmW1JlUKpsjmstz+oJxZHATMP64fymTkxRmyHU7bNktBkiI3i6k1cFXRPGEhrf2Uftnve/Zy2TEJ6ucnEpYmw5+LyZgAZVNLzFnUrE2FUbzG8I1yO2KYr00nvof4="
  # AWS_SECRET_ACCESS_KEY
  - secure: "lL7WaRHysuAKGLhMBbMyCk8yvRn4mmZeF+W7t4duh7/1DrGiPZ9kQwkfM54r5hLXPeKqqMyDjJs5kATlBgzg68dnwSaLFsbe3TqI9Zj258PgUf1+EYaK+vP9O9brHUUrmtqj6uFGtrP1Dqj2S8AUuTvrYtvSr7vGGitv4++n3AY="

before_install:

# hyrax-dependencies-build.tar.gz includes/makes the build directory
install:
- (cd $TRAVIS_BUILD_DIR && curl -s -O https://s3.amazonaws.com/opendap.travis.build/hyrax-dependencies-build.tar.gz) 
- tar -C $HOME -xzvf $TRAVIS_BUILD_DIR/hyrax-dependencies-build.tar.gz 

# - aws s3 ls s3://opendap.travis.build/
# - aws s3 cp s3://opendap.travis.build/hyrax-dependencies-build.tar.gz $TRAVIS_BUILD_DIR

before_script:
- printenv
- autoreconf --force --install --verbose

# The coverity_scan branch is built by the addon
jobs:
  stages:
  - name: build
    if:  branch NOT IN (debian)
    #used to be "!= coverity_scan"
  - name: package
    if:  branch != coverity_scan
  include:
  - stage: build
    script:
    - export LIBDAP_BUILD=main
    - ./configure --disable-dependency-tracking --prefix=$prefix
    - make -j7 && make check -j7 && make install
  - stage: build
    script: 
    - export LIBDAP_BUILD=asan
    - ./configure --disable-dependency-tracking --prefix=$prefix --enable-developer --enable-asan
    - make -j7 && make check -j7
  - stage: build
    script: 
    - export LIBDAP_BUILD=distcheck
    - ./configure --disable-dependency-tracking --prefix=$prefix --enable-developer
    - make distcheck -j7
  - stage: package
    script: 
    - export LIBDAP_BUILD=deb
    - mkdir -p $prefix/debbuild
    - docker run --volume $prefix/debbuild:/root --volume $TRAVIS_BUILD_DIR:/root/travis
                 --env os=ubuntu14 opendap/ubuntu14_hyrax_build:1.4 /root/travis/build-deb.sh
  - stage: package
    script: 
    - export LIBDAP_BUILD=centos7
    - mkdir -p $prefix/rpmbuild
    - docker run --volume $prefix/rpmbuild:/root/rpmbuild --volume $TRAVIS_BUILD_DIR:/root/travis
                 --env os=centos7 opendap/centos7_hyrax_builder:1.1 /root/travis/build-rpm.sh
  - stage: package
    script: 
    - export LIBDAP_BUILD=centos6
    - mkdir -p $prefix/rpmbuild
    - docker run --volume $prefix/rpmbuild:/root/rpmbuild --volume $TRAVIS_BUILD_DIR:/root/travis
                 --env os=centos6 opendap/centos6_hyrax_builder:1.1 /root/travis/build-rpm.sh

before_deploy:
- mkdir -p $TRAVIS_BUILD_DIR/package
- if test "$LIBDAP_BUILD" = "main"; then tar -C $HOME -czvf $TRAVIS_BUILD_DIR/package/libdap-build.tar.gz 
                                             --exclude 'install/deps*' --exclude 'install/rpmbuild*' install; fi
- if test "$LIBDAP_BUILD" = "deb"; then cp $prefix/debbuild/libdap_*_amd64.deb $TRAVIS_BUILD_DIR/package/; fi
- if test "$LIBDAP_BUILD" = "centos6"; then cp $prefix/rpmbuild/RPMS/x86_64/* $TRAVIS_BUILD_DIR/package/; fi
- if test "$LIBDAP_BUILD" = "centos7"; then cp $prefix/rpmbuild/RPMS/x86_64/* $TRAVIS_BUILD_DIR/package/; fi
- ls -lR $TRAVIS_BUILD_DIR/package

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: opendap.travis.build
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/package
  on:
    branch:
    - master
    - debian
    #- /^version-.*$/
    condition: $LIBDAP_BUILD =~ ^main|deb|centos7|centos6$

