# Build and test libdap

name: CI

env:
  prefix: ${{ github.workspace }}/build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ actions-test ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel

jobs:
  ubuntu-build:
    # Suppress this for the actions-test for now. a hack.
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: packages
        run:  sudo apt-get --yes install libxml2-dev uuid-dev libcurl4-openssl-dev libcppunit-dev
      - name: autoreconf
        run: autoreconf --force --install --verbose
      - name: configure
        run: ./configure --enable-developer --prefix=$prefix
      - name: make
        run: make --jobs=20
      - name: check
        run: make --jobs=20 check

  osx-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: packages
        run: brew install cppunit autoconf automake libtool
      - name: autoreconf
        run: autoreconf --force --install --verbose
      - name: configure
        run: ./configure --enable-developer --prefix=$prefix
      - name: make
        run: make -j20
      - name: make check
        run: make -j20 check

  # For info on the docker commands: https://www.petefreitag.com/item/903.cfm
  # and https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
  centos-7-build:
    runs-on: ubuntu-latest
    container:
      image: opendap/centos7_hyrax_builder:1.1

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: autoreconf
        run: autoreconf -fiv 
      - name: configure
        run: ./configure --enable-developer --prefix=$prefix
      - name: make
        run: make -j20
      - name: make check
        run: make -j20 check
      - name: make install
        run: make install
#      - name: upload artifact
#        uses: actions/upload-artifact@v2
#        with:
#          path: /hyrax-deps-centos7.tar.gz
#          name: hyrax-deps-centos7.tar.gz
