# This is centOS 7 rpm build. 

name: CI

env:
  prefix: ${{ github.workspace }}/build
  jobs: 16

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ feature/test-buildout ]
  pull_request:
    branches: [ feature/test-buildout ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel

jobs:
  centos-7-build:
    runs-on: ubuntu-latest
    container:
      image: opendap/centos7_hyrax_builder:1.3

    # packages step not here because the Docker container holds them already
    steps:

      - name: cache-bison
        id: cache-bison   # Used below in the 'if'
        uses: actions/cache@v2
        with:
          path: $prefix/deps
          key: bison-centos7-docker

      # build the depdendencies so that we don't have to update teh container
      # every time the deps change.
      - name: build bison dependency
        if: steps.bison-centos7-docker.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/OPENDAP/hyrax-dependencies
          cd hyrax-dependencies
          make --jobs=$jobs bison
      - name: checkout
        uses: actions/checkout@v2

      - name: autoreconf
        run: autoreconf -fiv

      - name: configure
        run: ./configure --enable-developer --prefix=$prefix

      - name: make
        run: make rpm --jobs=$jobs


      # Again, look around. see where things are at the end of the build.
      - name: home dir files
        run: ls -lR ~

      - name: upload to s3
        run: |
          yum install -y awscli
          #aws s3 cp /github/home/rpmbuild/RPMS/* s3://opendap.travis.build --recursive    
          #aws s3 cp /github/home/rpmbuild/RPMS/* s3://opendap.github.actions.build --recursive     
          #aws s3 cp /github/home/rpmbuild/RPMS/* s3://${{ secrets.AWS_BUCKET }} --recursive   
          #aws s3 cp /github/home/rpmbuild/RPMS/* s3://${AWS_BUCKET_NAME} --recursive 
          aws s3 cp /github/home/rpmbuild/RPMS/* s3://$AWS_BUCKET_NAME --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUILD_BUCKET }}
          #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_TRAVIS }}
          #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TRAVIS }}
          #AWS_BUCKET: ${{ secrets.AWS_BUCKET_TRAVIS }}

          